### PR TITLE
Added support for Autorest MS-Enum

### PR DESCRIPTION
**Pull request by henning-krause**
Added support for Autorest MS-Enum (https://github.com/Azure/autorest/blob/master/Documentation/swagger-extensions.md#x-ms-enum).

Can be enabled via
`cs
config.EnableSwagger(c =>
{
    c.EnableAutoRestSupportForEnums(AutoRestEnumSupportType.Enum);
}
`cs
This will inform AutoRest to create an enum (C# enum).
`
c.EnableAutoRestSupportForEnums(AutoRestEnumSupportType.StaticStrings)
`

will inform AutoRest to create an enum based on static strings

### CODE REVIEW

**Comment by gitfool** [comment]
:+1: Any progress on this? @henning-krause

**Comment by mms-** [comment]
Would also like to have this in the NuGet!

**Comment by gitfool** [comment]
Meanwhile, I've come up with a workaround that seems sufficient:
```c#
public class AutoRestEnumSchemaFilter : ISchemaFilter
{
    public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
    {
        foreach (var property in schema.properties.Where(x => x.Value.@enum != null))
        {
            property.Value.vendorExtensions.Add("x-ms-enum", new { name = property.Key });
        }
    }
}
```

**Comment by giacomelli** [comment]
In scenarios where the name of the property can be different from the name of the enum, we need a small modification in @gitfool solution:

```csharp
public class XmsEnumSchemaFilter : ISchemaFilter
{
    public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
    {
        foreach (var property in schema.properties.Where(x => x.Value.@enum != null))
        {
            // The name of the property can be different from the name of the enum. 
            var propertyType = type.GetProperty(property.Key, BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public).PropertyType;

            // Uses the name of the enum in x-ms-enum.
            property.Value.vendorExtensions.Add("x-ms-enum", new { name = propertyType.Name });
        }
    }
}
```

**Comment by gitfool** [comment]
@giacomelli Note that the above workaround is not necessary with the latest Swashbuckle, which can apply schema filters everywhere; so can use something like the following instead: [Swashbuckle.AutoRestExtensions/EnumTypeSchemaFilter.cs](https://github.com/gitfool/Swashbuckle/blob/edea12f54c0f54f2eb7237018f24de4163cdbe44/Swashbuckle.AutoRestExtensions/EnumTypeSchemaFilter.cs). 😉

**Comment by csharmath** [comment]
the solutions posted by @gitfool  or @giacomelli were throwing for me as the schema.properties was null, so adding a null check seems to have fixed it

```
public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
            if (schema.properties != null)
            {
                foreach (var property in schema.properties.Where(x => (x.Value?.@enum != null)))
                {
                    // The name of the property can be different from the name of the enum. 
                    var propertyType =
                        type.GetProperty(property.Key,
                            BindingFlags.IgnoreCase | BindingFlags.Instance | BindingFlags.Public).PropertyType;

                    // Uses the name of the enum in x-ms-enum.
                    property.Value.vendorExtensions.Add("x-ms-enum", new {name = propertyType.Name});
                }
            }
        }
```

But more importantly, is this still the recommendation ?

Many thanks btw for this as I just ran into the same thing with Autorest

**Comment by gitfool** [comment]
@csharmath Yeah you need to handle null schema.properties in the first workaround.

Like I said after that, that's not necessary any more, so I would just use the latest Swashbuckle with ApplyFiltersToAllSchemas and EnumTypeSchemaFilter. This will work everywhere (unlike the first workaround).

**Comment by csharmath** [comment]
thanks, will try that.

**Comment by domaindrivendev** [comment]
Swashbuckle is focused on generating accurate Swagger 2.0 descriptions of an API based on routes, controllers and models. That's a significant enough scope for one project without trying to generate extensions to the spec for supporting different downstream tools that consume it.

However, it provides rich extensibility options to customize as you see fit and @gitfool has made some good contributions and examples that demonstrate this, particularly as it relates to AutoRest. See his comment above - https://github.com/domaindrivendev/Swashbuckle/pull/629#issuecomment-267382954

**Pull request closed without merging**
