### PR TITLE
Exposing a Swagger by area for users mixing MVC and WebApi in a same project

### PR DESCRIPTION
**Pull request by rflechner**
Hi,

I saw multiple questions about areas handling in issues and stackoverflow.com.

My client is actually maintaining a WebApi containing some MVC's areas (I know it's not a very good practice but some peoples do that).
Now, he needs a swagger by area.

In this PR I propose to create a new NuGet "Swashbuckle.Areas" extending Swashbuckle.
This NuGet could be an addendum adding possibility to have a swagger (and a swagger UI) per area.

I added a usage example here: https://github.com/rflechner/Swashbuckle/blob/1fd1a62d606888f23c3549e3742dfba6103eae18/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs#L25

You can run the example project with config:

``` xml
<appSettings>
	<add key="isolateAreaSwaggers" value="true" />
</appSettings>
```

And go to urls:
- http://localhost:3429/swagger/ui/index
- http://localhost:3429/sampleone/swagger/ui/index
- http://localhost:3429/sampletwo/swagger/ui/index

image

PS. I introduced a notion of area description in Swashbuckle.Core but I did not introduced MVC and I did not changed dependencies.

Regards,

Romain.

### CODE REVIEW

**Comment by heldersepu** [comment]
Sounds like all you needed was to use versions...
Not sure why you did not consider that approach

**Comment by rflechner** [comment]
No, the client should create multiple applications but he prefers to have only one app with MVC areas 😃

**Comment by rflechner** [comment]
Yes you are right.
We will use versions.

Thanks for your help.

**Comment by heldersepu** [comment]
Also look at the latest UI, it has a filter by Tag:
http://swashbuckletest.azurewebsites.net/swagger/ui/index
You can use it like this:
http://swashbuckletest.azurewebsites.net/swagger/ui/index?filter=Image

The code is all here:
https://github.com/heldersepu/SwashbuckleTest

**Comment by magicben** [comment]
Hi @heldersepu 
Thank you @rflechner for this pull request.

I'm CTO at Finexkap and we got a need for this feature.
We have an APIs project with multiple areas depending on the interaction needed.
Users (partners) calling APIs endpoints of a specific area don't even know there are other areas: filter is not an option then as you can understand.
To help them integrate and test our APIs, Swagger is the best option and this is the choice we did.

@heldersepu, using versions is not so easy in our case, getting swagger per area is perfect to us and I think the @rflechner option of providing a non intrusive Nuget is great.
Why exatcly are you against this enhancement?

Regards,
Benoît.

**Comment by heldersepu** [comment]
Hello @magicben CTO at Finexkap,
 
I'm "against" this enhancement?
That is a strong word that I would keep for extreme cases (this feature not one of them) like:
- I'm against abuse of power
- I'm against radioactive fallout

But my comments on this enhancement reflect merely my take on the subject.
This enhancement shows Files changed (36) that's a lot of work to achieve something that looks a lot like what versions can already offer...

You even descrive it in plural "our APIs" that should be multiple api projects like some of mine:
http://nhc-noaa.azurewebsites.net/swagger
http://offleaseonly.azurewebsites.net/swagger
http://turoapi.azurewebsites.net/swagger
On the backend those could be using one common DB or not...
I'm a big fan of the Microservices architecture, small services, independent, and loosely coupled.

**Comment by heldersepu** [comment]
But don't get me wrong, I had quite a lot of disagreements with Swashbuckle...
If you look on my profile you will find [Swagger-Net](https://github.com/heldersepu/Swagger-Net)

That is my now detached fork of Swashbuckle. 
We agreed to disagree on the importance of some features and how fast to proceed. The owner recommended renaming my project that way it could be published to NuGet, which I do right now:
https://www.nuget.org/packages/Swagger-Net/
I've have incorporated so many features and fixed so many bugs that I no longer think the projects can one day be merged together.

**Pull request closed without merging**
