### PR TITLE
Fix for comments with JsonProperty attribute set for properties and fields

### PR DESCRIPTION
**Pull request by aphu**

### CODE REVIEW

**Comment by micheltol** [comment]
+1  will fix my issue.

**Comment by micheltol** [comment]
Incorprate dthis pull request in my local repo. Maybe I am doing something wrong but it doesn't seem to work: It is somehow taking over the wrong comments

    /// <summary>
    ///  VirtualReceipt Container
    /// </summary>
    public class VirtualReceiptItemContainer
    {
        /// <summary>
        /// Dictionary of used Payment methods
        /// </summary>
        [Required]
        public Dictionary<int, string> PaymentMethods { get; set; }
        /// <summary>
        /// Dictionary of used Statuses
        /// </summary>
        [Required]
        public Dictionary<int, string> Statuses { get; set; }
        /// <summary>
        /// Dictionary of used Types
        /// </summary>
        [Required]
        public Dictionary<int, string> Types { get; set; }
        /// <summary>
        /// Dictionary of used CurrencyCodes
        /// </summary>
        [Required]
        public Dictionary<int, string> CurrencyCodes { get; set; }
        /// <summary>
        /// Dictionary of used ServiceTokens
        /// </summary>
        [Required]
        public Dictionary<int, string> ServiceTokens { get; set; }
        /// <summary>
        /// List of <see cref="VirtualReceiptItem"/>
        /// </summary>
        [Required]
        public List<VirtualReceiptItem> Items { get; set; }
    }

    public class VirtualReceiptItem
    {
        /// <summary>
        /// TransactionId
        /// </summary>
        [JsonProperty(PropertyName = "e")]
        [Required]
        public string ExternalTransactionId { get; set; }
        /// <summary>
        /// Amount
        /// </summary>
        [JsonProperty(PropertyName = "a")]
        [Required]
        public int Amount { get; set; }
        /// <summary>
        /// Currency Id, Actual currency located in CurrencyCodes/>
        /// </summary>
        [JsonProperty(PropertyName = "c")]
        [Required]
        public int CurrencyCode { get; set; }
        /// <summary>
        /// PaymentMethod Id, Actual paymentMethod located in PaymentMethods/>
        /// </summary>
        [JsonProperty(PropertyName = "p")]
        [Required]
        public int PaymentMethod { get; set; }
        /// <summary>
        /// ReceiptDate, format: yyyy-MM-dd hh:mm:ss
        /// </summary>
        [Required]
        [JsonProperty(PropertyName = "r")]
        public string ReceiptDate { get; set; }
        /// <summary>
        /// ServiceToken Id, Actual servicetoken located in ServiceTokens/>
        /// </summary>
        [Required]
        [JsonProperty(PropertyName = "s")]
        public int ServiceToken { get; set; }
        /// <summary>
        /// Status Id, Actual status located in Statuses/>
        /// </summary>
        [Required]
        [JsonProperty(PropertyName = "u")]
        public int Status { get; set; }
        /// <summary>
        /// Type Id, Actual type located in Types/>
        /// </summary>
        [Required]
        [JsonProperty(PropertyName = "t")]
        public int Type { get; set; }

        public List<VirtualReceiptLineItem> Items { get; set; }
    }


Is resulting in a mixed up swagger page:
image

**Comment by domaindrivendev** [comment]
This is a known issue with the existing implementation - if you look closely at the code I already have a TODO: comment highlighting the deeper issue ...

Namely, a limitation in the application of ISchemaFilter, which is perfectly highlighted by this issue.

If you consider it's interface ...

    void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type);

there's an immediate problem if you need to modify properties on the Schema based on a corresponding MemberInfo on the system Type. There is no reliable way to correlate the two.

I think this interface will need to be adjusted to provide some additional context that maps Type members to their corresponding schema properties. Then, the XmlComments implementation can be easily fixed. Stay tuned for the fix ...

**Comment by domaindrivendev** [comment]
Should be fixed in latest version (pre-release) version

    Update-Package Swashbuckle -Pre

Can you please verify if you get a chance?

**Pull request closed without merging**
