### PR TITLE
Handle byte as integer, byte[] as string format=byte

### PR DESCRIPTION
**Pull request by jhancock93**
Addresses issue #640 by fixing CreatePrimitiveSchema to handle Byte[] as byte formatted string instead of Byte which should just be handled as a integer.

### CODE REVIEW

**Comment by domaindrivendev** [comment]
Hey there - thanks for this PR. Unfortunately, it's now invalid due to some license issues that I inadvertently introduced recently.

Sorry for the inconvenience but is there any chance you could pull the latest code and re-create the PR?

**Comment by jhancock93** [comment]
OK, rebased pull request branch on latest code.

**Comment by jhancock93** [comment]
If you need me to close this request on this branch and create a new pull request off a new branch, I can do that too if you prefer.

**Comment by jhancock93** [comment]
Based off the license issue, it sounds like we need a new pull request. Closing this one and will create another with a separate branch.

**Pull request closed without merging**
