### PR TITLE
AutoRest extensions

### PR DESCRIPTION
**Pull request by gitfool**
Following up from #799 (#776 Part II); I created an AutoRest extensions project.

The simplest usage is via the `SwaggerDocsConfig.ApplyAutoRestFilters` extension method:

``` c#
using Swashbuckle.AutoRestExtensions;
...
config.ApplyAutoRestFilters(codeGenerationSettings: new
{
    clientName = "MyProxy",
    useDateTimeOffset = true
}, nonNullableAsRequired: true);
```

... or the filters can be wired up manually as required.

Initial filters:
- CodeGenerationSettingsDocumentFilter
- EnumTypeSchemaFilter
- TypeFormatSchemaFilter
- NullableTypeSchemaFilter
- NonNullableAsRequiredSchemaFilter

### CODE REVIEW

**Comment by domaindrivendev** [comment]
@gitfool - I was thinking that "Swashbuckle.AutoRest" would be a separate project, in a separate repo, maintained independently (perhaps by yourself). Similar to this - https://github.com/rbeauchamp/Swashbuckle.OData.

Right now there's a lot of work planned for SB, in particular building the next-gen version that targets ASP.NET Core, and so I'm a little reluctant to increase the overall scope of SB and take on all of the additional maintenance that comes with that. I'd be more than happy to support such a project in any way I can - e.g. improving extensibility where necessary, links in the documentation etc.

**Comment by gitfool** [comment]
@domaindrivendev Sorry for the late reply; I took some time off.

I think you're right to avoid supporting AutoRest in Swashbuckle itself. It was just quick and easy for me to put the project together in the same repo and leverage the existing unit tests etc.

I don't exactly want ownership of this either, since it's not core to my concerns, so I'm not sure where to go from here. Ideally the AutoRest team would consider owning it, but I'd expect them to express the same reasons not to.

Looking at the changes again, they're very simple given the change to apply schema filters everywhere, so maybe it could be reduced to documentation?

**Comment by gitfool** [comment]
@domaindrivendev PS. Could you _release_ a new version of Swashbuckle with all these changes?

**Comment by Alegrowin** [comment]
@gitfool I have created a nuget using your pull request at https://github.com/Alegrowin/Swashbuckle.AutoRestExtensions

now it is also available here https://www.nuget.org/packages/Swashbuckle.AutoRestExtensions/1.0.0

**Comment by domaindrivendev** [comment]
Closing as I don't want to start supporting consumer-specific extensions in the Swashbuckle project. Generating a valid Swagger spec is a significant scope in itself.

A separate project that leverages SB's rich extensibility options is ideal:

https://github.com/Alegrowin/Swashbuckle.AutoRestExtensions

**Pull request closed without merging**
