### PR TITLE
Pretty Print option

### PR DESCRIPTION
**Pull request by GDoronin**
Pretty-Print output option for SwaggerDocsHandler implemented.
Test added.

### CODE REVIEW

**Comment by GDoronin** [comment]
@domaindrivendev Cool. Would you like me to also update the documentation?

**Comment by domaindrivendev** [comment]
That would be awesome - thanks!

**Comment by GDoronin** [comment]
Documentation updated in PR #662

**Comment by GreenMooseWork** [comment]
Will this be part of https://github.com/domaindrivendev/Swashbuckle.AspNetCore in a near future?

**Pull request merged**
