### PR TITLE
Add extensionpoints to SwaggerGenerator

### PR DESCRIPTION
**Pull request by kristofferahl**
Enables extending SwaggerGenerator through inheritance and overriding of virtual methods.

We have an api where we want to customize our Swagger documentation to make it as accurate as possible. Opening up SwaggerGenerator allows us to inherit and simply override the methods we need to customize.

I'd be happy to give this another go if the solution is not to your satisfaction.

### CODE REVIEW

**Comment by KarlEzy** [comment]
this is highly needed and a tiny fix, please merge!

**Comment by dariusdamalakas** [comment]
We'd love to have this too. 

Seem this PR has been ignored for some months already. I'd recommend squashing all commits into one, as it's just 1 file change, but otherwise the changes look ok.

Any idea whether there is an active maintainer who can review and accept this?

**Comment by domaindrivendev** [comment]
Apologies for the delay. I'm currently working working my way through the list of issues and prioritizing.

This particular fix is not top of the list.

Swashbuckle has a lot of extensibility built in with the range of configure options, operation, schema and document filters.

Philosophically, I don't believe that making all private methods virtual protected is a good approach for extensability - especially in a library. It breaks encapsulation - now I can't change the internals of the generator because consumers of the library could be coupled. I prefer to follow the GoF advice and "favor composition over inheritance".

Perhaps you could elaborate on the specific feature you're trying to achieve and we can collaborate on a different design?

**Comment by dariusdamalakas** [comment]
@domaindrivendev , thanks for responding. These are all valid points about encapsulation, and there are quite a few extensibility points, which should cover most of the cases. In light of this, the PR should be closed.

**Comment by dariusdamalakas** [comment]
@domaindrivendev , there's one missing extensibility point raised here: #651

**Comment by domaindrivendev** [comment]
Just circling back on this - thanks for the update.

**Pull request closed without merging**
