### PR TITLE
Add [SwaggerResponse] attribute

### PR DESCRIPTION
**Pull request by DavidDeSloovere**
Linked to #175 
This add the attribute, operation filter and tests.

### CODE REVIEW

**Comment by domaindrivendev** [comment]
Looks great - I'm just merging this in right now.

There is one use-case which is not addressed though and I'm trying to figure out the best way to support it. @dicksonl - I'd also appreciate your opinion on this too ...

The attribute approach is a great way to add additional (often error) responses to an operation description. It can also be used to override the model/description for a given status code (e.g. 200). However, there is no way to override the default status code. For example, if I want to indicate that an operation will return a 201 "as opposed to" 200 on success, the following won't work ...

    [SwaggerResponse(201, "Account Created")]
    public int CreateAccount(Account account)
    ...

This will describe two responses, the auto-generated "200" response and the additional "201" response which is not the desired result.

Although it may be slightly unexpected, I think the default responses should be cleared if one or more response-attributes are detected. In other words, using the attributes means the developer has opted to be "explicit" in describing responses for that operation and as such should provide all responses, including those in the 2xx range.

Let me know if this makes sense and I'll make the necessary changes.

**Comment by dicksonl** [comment]
Hi guys! @domaindrivendev  yeah, it would make sense to clear the default response model if more than one 2XX attribute is defined.

**Comment by DavidDeSloovere** [comment]
My first thought was solving it with a new attribute like [SwaggerResponseRemoveDefaults].
Explicit, the user is in control.

So, adding my own option, we have 3 choices:
1/ Remove defaults if any SwaggerResponse attribute
2/ Remove defaults in case of a 2xx SwaggerResponse attribute
3/ Remove default via extra attribute


MVC uses a pattern similar to option 3. you can add Authorize attribute filter globally. But decorated one action with [AllowAnonymous] to override.

**Comment by dicksonl** [comment]
I'd lean towards 2 or 3, developers may only want to create bad requests Attributes but still have 200 to be shown as default response in Swagger-ui.

**Comment by domaindrivendev** [comment]
Agreed - lets eliminate option 1 then!

I'm leaning toward 2) over 3). Looking at what I consider to be the most common scenario, i.e. changing the "success" response from "200" to something else (e.g. "201"), the following seems like a lot of noise, particularly if it's something I'm doing a lot ...

    [SwaggerResponseRemoveDefaults]
    [SwaggerResponse(201, typeof(Product))]
    public IActionResult CreateProduct(Product product)
    ....

I prefer the following for it's succintness ...

    [SwaggerResponse(201, typeof(Product))]
    public IActionResult CreateProduct(Product product)
    ....

Looking at a less likely scenario, multiple 2xx codes for the same action, you will need at least two attributes either way and it's actually arguable which approach is more explicit

    [SwaggerResponseRemoveDefaults]
    [SwaggerResponse(200, typeof(Product))]
    [SwaggerResponse(201, typeof(Product))]
    public IActionResult CreateProduct(Product product)
    ....

VS

    [SwaggerResponse(200, typeof(Product))]
    [SwaggerResponse(201, typeof(Product))]
    public IActionResult CreateProduct(Product product)
    ....

@andyalm - would love to hear your thoughts on this ...

**Comment by domaindrivendev** [comment]
Went with option 3) in the end to remove via additional attribute -  we can always change later if people It's now merged in - see https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/Controllers/SwaggerAnnotatedController.cs for an example.

**Comment by dicksonl** [comment]
Looks good

**Pull request closed without merging**
