### PR TITLE
Improve error when we can't find the given XML Comment file 

### PR DESCRIPTION
**Pull request by heldersepu**
Fix for Issue #1070

### CODE REVIEW

**Comment by paul3291** [comment]
should you throw a "FileNotFoundException" instead of "Exception"?

**Comment by domaindrivendev** [comment]
@heldersepu - I'm a tiny bit confused by this one. Doesn't the XPathDocument constructor throw a FileNotFoundException itself - why catch and throw the same error again?

**Comment by heldersepu** [comment]
@domaindrivendev 
we currently get a ```"Message": "An error has occurred."```
The idea is to  change it to some \thing a bit more descriptive:
```"Message": "XML Comment file not found!"```

**Comment by domaindrivendev** [comment]
@heldersepu - I understand the problem you're wanting to solve, I'm just not sure the approach you're taking is going to work. Without your change, the code will throw the following exception:

```csharp
FileNotFoundException("Could not find file '...../XmlComments.xml'")
```

And then with your change it essentially just changes the message a little:

```csharp
FileNotFoundException("XML Comment file not found!")
```

In both cases, when you deploy to production you're still just going to see the general 500 error message in the JSON response. This is because the default behavior of WebAPI __in production__ (and rightly so) is to omit exception details (including the message) from JSON responses. Doing so can expose the internals of your API implementation and that's an added security risk.

As a matter of interest, did you deploy you're change to production (I believe you mentioned it's in Azure) and see the more detailed response you're expecting. I'd be very surprised if the answer is yes.

**Comment by heldersepu** [comment]
Exactly, you are not sure...
But heck this is your project

**Comment by domaindrivendev** [comment]
I think it's perfectly reasonable that I "understand" changes before merging them in.

In this case, based on my current understanding of exception handling in WebAPI, I really don't see how the change you're proposing is going to result in a more meaningful message in production - where exception messages are omitted regardless. But, I could be missing something and that's why I ask if you've confirmed in production?

**Comment by domaindrivendev** [comment]
@heldersepu - I see you've closed all of your open PRs and I'm assuming this is due to frustration with some of my feedback. I'm sorry if this is the case as I'm extremely grateful for all the work you've been putting into supporting this project.

**Pull request closed without merging**
