### PR TITLE
Allow the SwaggerUI Document title to be configurable

### PR DESCRIPTION
**Pull request by heldersepu**

### CODE REVIEW

**Comment by heldersepu** [comment]
Fix for issue #1079

**Comment by sudarpo** [comment]
Why is this deleted?

**Comment by heldersepu** [comment]
@sudarpo why not?

**Comment by sudarpo** [comment]
@heldersepu Sorry i was confused. U deleted a branch that has been merged to master, which is not an issue.

btw.. the DocumentTitle option is missing / removed. Can we put it back? or this option was deleted due to some reason?

**Comment by heldersepu** [comment]
@sudarpo I guess you still confused, the DocumentTitle option is there:
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/Application/SwaggerUiConfig.cs#L23
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.WebHost/Nuget/Content/App_Start/SwaggerConfig.cs.pp#L185

**Comment by sudarpo** [comment]
@heldersepu oh this issue is for NET Framework version.. not Core.
Forgot to say I'm using AspNetCore version.

**Comment by heldersepu** [comment]
@sudarpo on that case you are on the wrong project

**Pull request merged**
