### PR TITLE
WIP: Upgrade Swagger UI to 3.x

### PR DESCRIPTION
**Pull request by bjornharrtell**

### CODE REVIEW

**Comment by carlmon** [comment]
See this PR with the v3 UI: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/453

**Comment by bjornharrtell** [comment]
Glad to see @carlmon finished this before I had time to revisit. :)

The original author has asked to transfer maintainership so I'm sad to hear about the differences @heldersepu. Your fork still lists "Auto-generated Swagger 2.0" but it looks like you recently completed the upgrade to 3.x too?

**Comment by heldersepu** [comment]
Swagger 2.0 refers to:
https://swagger.io/specification/

when you say upgrade to 3.x you are referring to swagger-ui:
https://github.com/swagger-api/swagger-ui

Two different things, see the chart here:
https://github.com/swagger-api/swagger-ui#compatibility

**Comment by bjornharrtell** [comment]
Ah, of course @heldersepu I was mixing things up sorry.

**Comment by bondjw07** [comment]
Just checking in on this as we just recently started using swashbuckle but noticed that it's on the current version of the Swagger UI.  Just wondering if:
1. There are any plans of updated this here
2. If there is any way to inject the changes manually to use the updated UI
3. Or if you think I should just give up and move to swagger-net to get these updates

**Comment by heldersepu** [comment]
For the record this PR is not ready to merge, many more change are required on the index.html

**Comment by ntregillus** [comment]
I am attempting to use Swashbuckle.Examples which is correctly rendering the appliation/json response examples (see definition here https://swagger.io/docs/specification/2-0/adding-examples/) 

basically the examples i am rendering per open api standard are appearing incorrectly:

image
but the editor at https://editor.swagger.io/ does display it correctly:
image

**Pull request closed without merging**
