### PR TITLE
Multi target net45 452

### PR DESCRIPTION
**Pull request by mattlangis**

### CODE REVIEW

**Comment by mattlangis** [comment]
I updated the project so it support multiple .NET Frameworks (from 4.0 to 4.5.2). I used Caitlyn ( http://caitlyn.codeplex.com/ )
I also had to disable the auto packaging because of a NuGet bug in 2.8.50926. 
Finally, I can also add a Powershell script that build the both nuget package, it would be simple too.

**Comment by andyalm** [comment]
Can you provide some more context on why you would like to see this change made? Swashbuckle currently targets .NET 4.0, but should be consumable by applications targeting .NET 4.5 or 4.5.1, 4.5.2, etc. In fact, I use it on a number of projects that target .NET 4.5.2. The only value I can see for actually compling Swashbuckle specifically to .NET 4.5 or later was if it wanted to make use of features that are only available in 4.5 or greater. However, I don't necessarily see any of those features in your pull request.

**Comment by mattlangis** [comment]
Hi Andy,

We have a project that is on 4.5.1 that is deployed on an Azure Web Services. I had the exact same issue as in here:
https://github.com/domaindrivendev/Swashbuckle/issues/75

We have set the bindingRedirect and nothing worked. I think it's because we use "Microsoft.AspNet.WebApi.Core 5.2.3" and you guys use 4.0.x. Both are incompatible as far as I know. This is why I forked your (awesome) project and made this custom version. Now, it works perfectly.

The bug can only be seen when there's a new filter added (like an IOperationFilter).

**Comment by jayoungers** [comment]
I'm running into this issue as well on the current 5.1.5 version (using webapi 5.2.3 on .net v4.5):

A first chance exception of type 'System.IO.FileNotFoundException' occurred in Swashbuckle.Core.dll

Additional information: Could not load file or assembly 'System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by mattlangis** [comment]
@jayoungers, try to clone the latest version of Swashbuckle and change the targeted .Net version. You might have to update some dependent packages (I think there's at least one, Microsoft.AspNet.WebApi.Core, the problematic one) and it should work.

It's also why I tried to find an alternative with my pull request, so Swashbuckle would work on both 4.0- and 4.5+.

**Comment by jayoungers** [comment]
I updated the framework version along with the nuget packages (had to also upgrade the nuget.exe included with the solution - I didn't even know each solution had its own version of nuget), and referenced Swashbuckle.Core.dll in my project.

Everything starts up great without any issues; however, actually going to the Swagger UI piece throws a bunch of asset not found exceptions from the asset provider.  Outside of the core.dll file, what else did you need to add to get the Swagger UI piece to function? 

Thanks!

**Comment by mattlangis** [comment]
I used to work on a Windows Azure app that was using .Net Framework 4.5.2 and I had a similar issue.

Since you have updated the framework, it's hard to say from here. I think you can try the solution in this issue: https://github.com/domaindrivendev/Swashbuckle/issues/75

**Pull request closed without merging**
